# Generated by Django 3.2.12 on 2022-08-10 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20220810_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='head_images',
        ),
        migrations.AddField(
            model_name='post',
            name='head_image',
            field=models.ImageField(blank=True, upload_to='blog/images/%Y/%m/%d/'),
        ),
    ]
