# Generated by Django 3.2.12 on 2022-08-11 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_post_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='title1',
        ),
    ]
