# Generated by Django 3.2.12 on 2022-08-11 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_rename_title_post_title1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title1',
            new_name='title',
        ),
    ]
